# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- demobranch

pool:
  name: myRaspberrypi 

steps:
- script: |
    sudo apt update
    sudo apt upgrade -y   
  displayName: 'Install Apache Ant and Maven on Raspberry Pi'

# Step 3: Download and install the latest version of Maven
- script: |        
    MAVEN_VERSION=3.9.7
    wget https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
    sudo tar -xvzf apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /opt
    sudo rm -rf /opt/maven
    sudo ln -s /opt/apache-maven-${MAVEN_VERSION} /opt/maven
  displayName: 'Download and install latest Maven'

- script: |
    export M2_HOME=/opt/maven
    export PATH=$PATH:$M2_HOME/bin
    mvn -v
  displayName: 'Set Maven environment and verify'

- script: |
    export M2_HOME=/opt/maven
    export PATH=$PATH:$M2_HOME/bin
    mvn clean install
  displayName: 'Run Maven build'

# Step 4: Set up Maven environment variables
#- script: |
#    echo "export M2_HOME=/opt/maven" | sudo tee -a /etc/profile.d/maven.sh
#    echo "export MAVEN_HOME=/opt/maven" | sudo tee -a /etc/profile.d/maven.sh
#    echo "export PATH=$PATH:/opt/maven/bin" | sudo tee -a /etc/profile.d/maven.sh
#    source /etc/profile.d/maven.sh
#  displayName: 'Set Maven environment variables'


