# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- demobranch

pool:
  name: myRaspberrypi

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    sudo apt update
    sudo apt upgrade -y
    sudo apt install -y docker.io
  displayName: 'Install Docker on Raspberry Pi'

# Step 2: Start Docker and enable it to run on startup
- script: |
    sudo systemctl enable docker
    sudo systemctl start docker
  displayName: 'Start Docker and enable on startup'

# Step 3: Verify Docker installation
- script: |
    docker --version
    sudo systemctl status docker
  displayName: 'Verify Docker Installation'

# Step 4: (Optional) Add the current user to the Docker group (to run Docker without sudo)
- script: |
    sudo usermod -aG docker $USER
  displayName: 'Add user to Docker group'