# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- demobranch

pool:
  name: myRaspberrypi


steps:
# Ensure Maven and Java are properly set
- script: |
    export JAVA_HOME=/home/pi/.sdkman/candidates/java/17.0.8-tem
    export PATH=$JAVA_HOME/bin:$PATH
    export M2_HOME=/opt/maven
    export PATH=$M2_HOME/bin:$PATH
    java -version
    mvn -v
  displayName: 'Verify Maven and Java Installation'

# Run Maven Package
- script: |
    export JAVA_HOME=/home/pi/.sdkman/candidates/java/17.0.8-tem
    export PATH=$JAVA_HOME/bin:$PATH
    export M2_HOME=/opt/maven
    export PATH=$M2_HOME/bin:$PATH
    mvn -f pom.xml -Xmx3072m package
  displayName: 'Run Maven Package'
