# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- demobranch

pool:
  name: myRaspberrypi

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    curl -s "https://get.sdkman.io" | bash
    source "$HOME/.sdkman/bin/sdkman-init.sh"
  displayName: 'Install SDKMAN!'

- script: |
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk install java 17.0.8-tem  # Install a specific version (17.0.8 from Temurin)
    java -version  # Verify the installation
  displayName: "Install Java 17"
